### PR TITLE
Rework geometry documentation

### PR DESCRIPTION
**Pull request by SeanCurtis-TRI**
1. Move render documentation into the render folder.
2. Change rhetoric for distinguishing the render engine implementations.

---
This change is [Reviewable](https://reviewable.io/reviews/tehbelinda/drake/1)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
So, here's the big reworking. Take a look and if you like it, you can merge it into your branch.

**Comment by SeanCurtis-TRI** [comment]
Try enabling Reviewable for this repo to facilitate review.

**Comment by SeanCurtis-TRI** [comment]
Test ping

**Review by tehbelinda — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tehbelinda/drake/1)* status: all files reviewed, 11 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[geometry/render/render_doxygen.h, line 16 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw-ZM79BNZ23lKGOSae:-Lw-ZM79BNZ23lKGOSaf:b-dy5jru) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L16)):*
> ```objc
>  Drake includes *two* implementations of that API:
> 
>    - RenderEngineVtk - an GPU-based rasterization renderer
> ```

nit: A GPU-based?
___
*[geometry/render/render_doxygen.h, line 21 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw07Beg088nSsG9A6nr:-Lw07Beh6Ej7NLl4CbCL:b1agfj6) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L21)):*
> ```objc
>  These implementations differ in many ways:
> 
>    - support of the API (i.e., how complete is the implementation)
> ```

should support be capitalised? like the other two points below
___
*[geometry/render/render_doxygen.h, line 26 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw07RHd1c79uDFdV24Y:-Lw07RHd1c79uDFdV24Z:bi1bkl2) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L26)):*
> ```objc
> 
>  Picking the right renderer for your simulated sensors will be based on
>  considering those differences and picking the trade off that best suits your
> ```

trade off -> trade-off?
___
*[geometry/render/render_doxygen.h, line 41 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw-Za9lDVelW3MtgCGZ:-Lw-Za9lDVelW3MtgCG_:b-udyxn3) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L41)):*
> ```objc
>  There's little to elaborate over that indicated by the table.
> 
>    - RenderEngineVTK: Full support
> ```

I think it would be helpful to at least elaborate what is covered by full, ie color + depth + label
___
*[geometry/render/render_doxygen.h, line 60 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw03QtvDwD6SbTSws-C:-Lw03QtvDwD6SbTSws-D:bxkw8l) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L60)):*
> ```objc
> 
>  The current API is simple and precludes sophisticated definitions of lights and
>  materials. As the API matures, these additional features are added the fidelity
> ```

this sentence doesn't make sense to me , did you mean something more like: As the API matures and these additional features are added, the fidelity differences between...
___
*[geometry/render/render_doxygen.h, line 73 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw04u0jEgmfIql0qY_Y:-Lw04u0jEgmfIql0qY_Z:b-l72346) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L73)):*
> ```objc
>  CPUs lead to shorter render times.
> 
>  The performance of RenderEngienVtk will depend on the quality of the GPU and
> ```

typo RenderEngienVtk -> RenderEngineVtk
___
*[geometry/render/render_doxygen.h, line 74 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw04wmJ0o0sGp1ff8M2:-Lw04wmJ0o0sGp1ff8M3:b-jgrou9) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L74)):*
> ```objc
> 
>  The performance of RenderEngienVtk will depend on the quality of the GPU and
>  its driver. A more power graphics card with an up-to-date driver will likely
> ```

A more powerful
___
*[geometry/render/render_doxygen.h, line 99 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw05POW3wUfFoH0bY5X:-Lw05POW3wUfFoH0bY5Y:b-bnp4rt) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L99)):*
> ```objc
>  the same direction, with the same intrinsic properties. In other words, each
>  should produce the same output image. This provides a measure of the
>  scalability as a simulation includes multiple cameras.
> ```

I had to re-read this to fully understand it. I think just saying 'includes multiple cameras' doesn't suggest the growth that should go along with scale. Maybe something like 'increases its number of cameras'?
___
*[geometry/render/render_doxygen.h, line 101 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw06BKm3Ar5LjriwTkY:-Lw06BKn9FohbQrCtbQH:byfx7k6) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L101)):*
> ```objc
>  scalability as a simulation includes multiple cameras.
> 
>  The output image can be configured to arbitrary size. For both RenderEngine
> ```

nit: an arbitrary?
___
*[geometry/render/render_doxygen.h, line 158 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw06QCG6uc0sr0I9wlw:-Lw06QCG6uc0sr0I9wlx:bg862px) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L158)):*
> ```objc
> 
>  ```
>  BenchmarkName/TestName/camera_count/sphere_count/image_width/image_height
> ```

sphere_count/camera_count - they should be swapped
___
*[geometry/render/render_doxygen.h, line 194 at r1](https://reviewable.io/reviews/tehbelinda/drake/1#-Lw06jR31V4dZGP47yYt:-Lw06jR31V4dZGP47yYu:bhkxi0z) ([raw file](https://github.com/tehbelinda/drake/blob/63de1097c2b421c66db8bbf1713916684834f440/geometry/render/render_doxygen.h#L194)):*
> ```objc
>        increase in time for both color and depth, but a (roughly) 20X increase
>        for label.
>      - RenderEngineVtk also increased a factor of 10X when path-tracing the
> ```

this should be RenderEngineOspray

**Review by tehbelinda — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tehbelinda/drake/1)* status: all files reviewed, 11 unresolved discussions (waiting on @SeanCurtis-TRI)

**Review by tehbelinda — COMMENTED** [review]
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tehbelinda/drake/1)* status: 6 of 11 files reviewed, 11 unresolved discussions (waiting on @SeanCurtis-TRI)

**Pull request merged**
